"""Agent-facing image tools.

Contract (per protoAgent's tool idiom): every tool returns a readable string —
markdown with the saved image's signed ``/media/`` URL on success (the console
renders it inline), or an ``Error: …`` line the model can act on. Never raises.

Image references: tools accept a prior result's media id (each success message
names it), a ``/media/<file>?sig=…`` URL, a ``data:image/...`` URL, or an
absolute file path. Generated bytes never enter the model's context as text —
when ``show_model`` is on they ride the multimodal envelope (#1930) instead.
"""

from __future__ import annotations

import base64
import struct
from pathlib import Path

from langchain_core.tools import tool

from . import client

_registry = None
CFG: dict = {}

_DEFAULTS = {
    "gen_model": "protolabs/qwen-image",
    "fast_gen_model": "protolabs/qwen-image-turbo",
    "edit_model": "protolabs/qwen-image-edit",
    "chat_model": "protolabs/qwen-image-chat",
    "bgremove_model": "protolabs/qwen-image-bgremove",
    "region_model": "protolabs/qwen-image-region-edit",
    "outpaint_model": "protolabs/qwen-image-outpaint",
    "identity_model": "protolabs/krea2-identity-edit",
    "realism_identity_model": "protolabs/krea2-identity-edit-realism",
    "typography_model": "protolabs/ideogram-4",
    "default_size": "1024x1024",
    "timeout_s": 300,
    "show_model": True,
}


def configure(registry) -> None:
    global _registry
    _registry = registry
    CFG.clear()
    CFG.update(_DEFAULTS)
    CFG.update({k: v for k, v in dict(getattr(registry, "config", {}) or {}).items() if v is not None})
    client.configure(CFG)


def get_tools() -> list:
    return [generate_image, edit_image, identity_edit, region_edit,
            remove_background, compose_images, outpaint_image, typography_image]


# ---------------------------------------------------------------- helpers

def _resolve_image(ref: str) -> bytes:
    """Media id / signed /media/ URL / data URL / file path → raw bytes."""
    ref = (ref or "").strip()
    if not ref:
        raise ValueError("empty image reference")
    if ref.startswith("data:"):
        if "," not in ref:
            raise ValueError("malformed data URL")
        return base64.b64decode(ref.split(",", 1)[1])
    if "/media/" in ref:
        from infra.media import resolve_media

        name = ref.split("/media/", 1)[1].split("?", 1)[0]
        hit = resolve_media(name)
        if hit is None:
            raise ValueError(f"unknown media file {name!r}")
        return hit[0].read_bytes()
    if "/" not in ref:
        from infra.media import media_dir

        for f in sorted(media_dir().glob(f"{ref}.*")):
            if f.suffix != ".json" and not f.name.startswith("."):
                return f.read_bytes()
        raise ValueError(f"no media with id {ref!r} — use the id from a previous tool result")
    p = Path(ref)
    if p.is_file():
        return p.read_bytes()
    raise ValueError(f"can't resolve image reference {ref!r}")


def _png_dims(raw: bytes) -> str:
    if len(raw) >= 24 and raw[:8] == b"\x89PNG\r\n\x1a\n":
        w, h = struct.unpack(">II", raw[16:24])
        return f"{w}x{h}"
    return "image"


def _finish(raw: bytes, caption: str, meta: dict) -> str:
    """Persist to the core media store and build the tool result."""
    ref = _registry.save_media(raw, "image/png", meta)
    alt = " ".join((caption or "generated image").split())[:120].replace("[", "(").replace("]", ")")
    text = (
        f"Done — {_png_dims(raw)} image saved as `{ref.id}`.\n\n"
        f"To show the user the image, include this markdown line VERBATIM "
        f"(exact URL, do not paraphrase it away) in your reply:\n"
        f"![{alt}]({ref.url})\n\n"
        f"Pass `{ref.id}` as the image reference to edit this result further."
    )
    if CFG.get("show_model", True):
        try:
            from graph.sdk import multimodal_tool_result

            return multimodal_tool_result(text, images=[{"b64": base64.b64encode(raw).decode(),
                                                         "mime": "image/png"}])
        except (ValueError, ImportError):
            pass  # over the core size cap (or old host) — inline markdown still renders
    return text


def _err(e: Exception) -> str:
    try:
        import httpx

        if isinstance(e, httpx.HTTPStatusError):
            detail = ""
            try:
                detail = (e.response.json().get("error") or {}).get("message", "")
            except ValueError:
                detail = e.response.text[:200]
            hint = " (alias missing from the gateway model_list?)" if e.response.status_code == 404 else ""
            return f"Error: gateway returned {e.response.status_code}{hint}: {detail or 'no detail'}"
        if isinstance(e, httpx.TimeoutException):
            return ("Error: gateway timed out — the render may still be queued on ComfyUI. "
                    "Try once more, or raise timeout_s in the protobanana plugin settings.")
    except ImportError:
        pass
    return f"Error: {type(e).__name__}: {e}"


def _seed(seed: int) -> int | None:
    return seed if seed >= 0 else None


# ------------------------------------------------------------------ tools

@tool
async def generate_image(prompt: str, size: str = "", seed: int = -1, negative_prompt: str = "",
                         draft: bool = False) -> str:
    """Generate an image from a text prompt.

    Args:
        prompt: What to draw — subject, style, composition, lighting.
        size: WxH like "1024x1024" (default from plugin settings).
        seed: Fixed seed for reproducibility; -1 = random.
        negative_prompt: What to avoid (optional).
        draft: True = fast 4-step draft (~10s, great for prototyping/iterating);
            False = full-quality render (~30s). Use draft when the user wants
            quick concepts, options, or is iterating on a prompt.
    Returns markdown with the saved image and its media id, or a readable error.
    """
    try:
        model = CFG["fast_gen_model"] if draft else CFG["gen_model"]
        raw = await client.generate(model, prompt, size or CFG["default_size"],
                                    seed=_seed(seed), negative_prompt=negative_prompt or None)
        return _finish(raw, prompt, {"tool": "generate_image", "prompt": prompt, "model": model,
                                     "draft": draft})
    except Exception as e:
        return _err(e)


@tool
async def edit_image(image_ref: str, prompt: str, seed: int = -1) -> str:
    """Edit an existing image with a natural-language instruction.

    Good for global/semantic changes ("make it night", "turn the car red",
    "watercolor style"). For changing ONE object precisely, prefer region_edit;
    for keeping a person's face intact, prefer identity_edit.

    Args:
        image_ref: A media id from a previous result, a /media/ URL, a data: URL, or a file path.
        prompt: The edit instruction.
        seed: Fixed seed; -1 = random.
    Returns markdown with the edited image and its media id, or a readable error.
    """
    try:
        raw = await client.edit(CFG["edit_model"], prompt, _resolve_image(image_ref),
                                fields={"seed": _seed(seed)})
        return _finish(raw, prompt, {"tool": "edit_image", "prompt": prompt, "source": image_ref})
    except Exception as e:
        return _err(e)


@tool
async def identity_edit(image_ref: str, prompt: str, person_ref: str = "",
                        grounding_px: int = 0, seed: int = -1, realism: bool = False) -> str:
    """Edit or restage a photo while preserving a person's identity/likeness (Krea 2).

    Two modes:
    - Single-ref: image_ref is the person's photo; prompt restyles/restages them.
    - Two-ref: image_ref is the SCENE, person_ref is the PERSON to place into it
      (this ordering is load-bearing — swapping them degrades identity sharply).

    Args:
        image_ref: The photo to edit (single-ref) or the scene (two-ref).
        prompt: The edit/staging instruction.
        person_ref: The person's reference photo (two-ref mode only).
        grounding_px: Quality dial 512–1536 (0 = default 768). Lower favors
            following the edit instruction; higher favors facial likeness.
        seed: Fixed seed; -1 = random.
        realism: Set true when the subject is a human/portrait and the result
            should look like a natural photograph — adds a realism adapter that
            markedly improves face quality and skin texture. Leave false for
            stylized/illustrated/non-photographic results.
    Returns markdown with the result and its media id, or a readable error.
    """
    try:
        fields: dict = {"seed": _seed(seed)}
        if grounding_px:
            fields["grounding_px"] = grounding_px
        if person_ref.strip():
            person = _resolve_image(person_ref)
            fields["person_image"] = "data:image/png;base64," + base64.b64encode(person).decode()
        model = CFG["realism_identity_model"] if realism else CFG["identity_model"]
        raw = await client.edit(model, prompt, _resolve_image(image_ref), fields=fields)
        return _finish(raw, prompt, {"tool": "identity_edit", "prompt": prompt,
                                     "two_ref": bool(person_ref.strip()), "realism": realism})
    except Exception as e:
        return _err(e)


@tool
async def region_edit(image_ref: str, region: str, prompt: str, seed: int = -1) -> str:
    """Edit ONE region/object of an image, leaving everything else untouched
    (SAM-grounded segmentation + inpaint).

    Args:
        image_ref: The image to edit (media id, /media/ URL, data: URL, or path).
        region: What to target, as a short noun phrase — "the red car", "her hat".
        prompt: What the region should become.
        seed: Fixed seed; -1 = random.
    Returns markdown with the result and its media id, or a readable error.
    """
    try:
        raw = await client.edit(CFG["region_model"], prompt, _resolve_image(image_ref),
                                fields={"grounding": region, "seed": _seed(seed)})
        return _finish(raw, f"{region} → {prompt}",
                       {"tool": "region_edit", "region": region, "prompt": prompt})
    except Exception as e:
        return _err(e)


@tool
async def remove_background(image_ref: str) -> str:
    """Remove an image's background, leaving the subject on transparency
    (sticker/cutout).

    Args:
        image_ref: The image (media id, /media/ URL, data: URL, or path).
    Returns markdown with the cutout and its media id, or a readable error.
    """
    try:
        raw = await client.edit(CFG["bgremove_model"], "remove background", _resolve_image(image_ref))
        return _finish(raw, "background removed", {"tool": "remove_background", "source": image_ref})
    except Exception as e:
        return _err(e)


@tool
async def compose_images(image_refs: list[str], prompt: str) -> str:
    """Compose 2–3 reference images into one new image (subjects, products,
    styles combined per the prompt).

    Args:
        image_refs: 2–3 references (media ids, /media/ URLs, data: URLs, or paths).
        prompt: How to combine them — who/what goes where, style, setting.
    Returns markdown with the composition and its media id, or a readable error.
    """
    try:
        refs = [r for r in (image_refs or []) if str(r).strip()]
        if not 2 <= len(refs) <= 3:
            return f"Error: compose_images needs 2–3 image references, got {len(refs)}."
        raw = await client.chat_compose(CFG["chat_model"], prompt, [_resolve_image(r) for r in refs])
        return _finish(raw, prompt, {"tool": "compose_images", "prompt": prompt, "refs": len(refs)})
    except Exception as e:
        return _err(e)


@tool
async def outpaint_image(image_ref: str, prompt: str = "", left: int = 0, top: int = 0,
                         right: int = 0, bottom: int = 0, seed: int = -1) -> str:
    """Extend an image's canvas outward (outpaint) by pixel margins.

    Args:
        image_ref: The image (media id, /media/ URL, data: URL, or path).
        prompt: What the new areas should contain (empty = continue the scene).
        left: Pixels to add on the left.
        top: Pixels to add on top.
        right: Pixels to add on the right.
        bottom: Pixels to add on the bottom.
        seed: Fixed seed; -1 = random.
    Returns markdown with the extended image and its media id, or a readable error.
    """
    try:
        if not any((left, top, right, bottom)):
            return "Error: give at least one non-zero margin (left/top/right/bottom)."
        raw = await client.edit(CFG["outpaint_model"], prompt or "extend the scene",
                                _resolve_image(image_ref),
                                fields={"left": left, "top": top, "right": right,
                                        "bottom": bottom, "seed": _seed(seed)})
        return _finish(raw, prompt or "outpainted", {"tool": "outpaint_image", "prompt": prompt})
    except Exception as e:
        return _err(e)


@tool
async def typography_image(prompt: str, size: str = "", seed: int = -1) -> str:
    """Generate a text-heavy image — poster, logo, sign, title card — with
    accurate typography (Ideogram 4). Put the exact words to render in double
    quotes inside the prompt: a poster saying "GRAND OPENING".

    Note: this model has a built-in, stochastic safety refusal — a flat gray
    result means it declined. That refusal is deliberate and NOT auto-retried;
    reword the prompt or ask the user before trying again.

    Args:
        prompt: The design brief, with literal text in double quotes.
        size: WxH like "1024x1024" (default from plugin settings).
        seed: Fixed seed; -1 = random.
    Returns markdown with the image and its media id, or a readable error.
    """
    try:
        raw = await client.generate(CFG["typography_model"], prompt, size or CFG["default_size"],
                                    seed=_seed(seed))
        return _finish(raw, prompt, {"tool": "typography_image", "prompt": prompt,
                                     "model": CFG["typography_model"]})
    except Exception as e:
        return _err(e)
